### ISSUE TITLE
Add ResidualCapacity for transmission

### ISSUE THREAD

**Issue by abhishek0208** [OSeMOSYS/osemosys_global#10]
The present version only includes capacities for all powerplants. Existing capacities of transmission lines - both intra- and inter-country - need to be included. 

Note: All lines are considered as bi-directional. Values for each direction is provided and should be allocated to the appropriate `MODE_OF_OPERATION`.

**Comment by maartenbrinkerink** [comment]
Just a clarification, not all lines are bi-directional. There can be large differences in certain cases, for example there is transmission capacity of just above 5 GW from NA-CAN-NL to NA-CAN-QC yet 0 GW the other way around.
