### ISSUE TITLE
[FEATURE] Functionality for multiple solvers 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#117]
### Idea

The current workflow is fully open-source and uses CBC to solve the model. It would be nice to include a solver type in the configuration file to allow the user to select between a variety of open or closed source solvers. That way, if the user have access to a closed solver (ie. Gurobi, CPLEX...) they can use that 

### Suggested Soltuion

Update the snakemake rule `cbc_solve` to be a more general rule (ie `solve`) that will read in the configuration solver parameter. Or introduce logic into the snakefile to select an appropriate solve rule (ie. `solve_gurobi`, `solve_cplex`...) based on the configuration file parameter

**Comment by willu47** [comment]
I've developed the following rule which uses a if,then,else switch in the shell to choose between two alternatives (cbc or gurobi):

```python
rule solve_lp:
    message: "Solving the LP for '{output}' using {config[solver]}"
    input:
        "results/{scenario}/{model_run}.lp"
    output:
        json="results/{scenario}/{model_run}.json",
        solution="results/{scenario}/{model_run}.sol",
    log:
        "results/solver_{scenario}_{model_run}.log"
    params:
        ilp="results/{scenario}/{model_run}.ilp"
    benchmark:
        "benchmarks/solver/{scenario}_{model_run}.tsv"
    resources:
        mem_mb=3000,
        disk_mb=33
    threads:
        1
    shell:
        """
        if [ {config[solver]} = gurobi ]
        then
          gurobi_cl OutputFlag=0 Method=2 Threads={threads} ResultFile={output.solution} ResultFile={output.json} ResultFile={params.ilp} {input} > {log}
        else
          cbc {input} solve -sec 1500 -solu {output.solution} > {log}
        fi
        """
```

where a config file contains the following entry
```
# Choose a solver, choices: 'cbc' or 'gurobi'
solver: cbc
```

**Comment by trevorb1** [comment]
Thanks for the code suggestion @willu47 ! This worked out great !
