### ISSUE TITLE
[BUG] Conda environment takes a long time to install 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#140]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

When importing the conda environment via `conda env create -f workflow/envs/osemosys-global.yaml`, some users are experiencing very long times for the installation (up to 7hrs). 

### Expected Behavior

Since we are using a fairly small number of packages, most/all of which are well maintained, it shouldn't be taking this long. I would think this should only take on the order of 2-15min. 

### Steps To Reproduce

1. Install Miniconda
2. Run the command `conda env create -f workflow/envs/osemosys-global.yaml`

### Operating System

All

**Comment by maartenbrinkerink** [comment]
@trevorb1 are there any recurring elements between these users that are different than wat you use? e.g. operating system, python version?

**Comment by trevorb1** [comment]
The user I heard from managed to install it on Mac, but not on Windows. I use Linux and it seems to work fine there. The environment file specifies a min python version, so I would think that would be okay, but you never know. I will try installing it on a Windows machine and check compatibility with python 3.11 since that just recently came out. 

The other thing I noticed was that I put sklearn under pip install rather than conda install in the environment file. I think that was just a mistake, but it shouldn't change functionality (ie. shouldn't be causing the issue in #141). That might be the culprit behind long install times though

**Comment by tniet** [comment]
Just installed today on a machine running Linux (spec below) and it took ~12 minutes to solve/build the environment.

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Xeon(R) CPU E3-1240L v5 @ 2.10GHz
Stepping:            3
CPU MHz:             801.712
CPU max MHz:         3200.0000
CPU min MHz:         800.0000
BogoMIPS:            4199.88
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

**Comment by tniet** [comment]
And sklearn didn't install correctly...
