### ISSUE TITLE
[BUG] Pandas `v2.0` breaks scripts

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#155]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

When running the workflow on pandas version 2 and higher, the scripts break. Im not sure if it is all the scripts, but def the `demand_projection` and `timeslice` scripts break. Seems to be an issue with the handling of datetimes

### Steps To Reproduce

1. Create the environment from the `osemosys-global.yaml` file
2. Run the workflow

### Operating System

Linux

### Anything else?

Before merging the PR to address this issue ticket, make sure you remove the version restriction in the `osemosys-global.yaml` file!

**Comment by Simone111git** [comment]
Just to add - also experiencing the same issue on a MAC operating system
