### ISSUE TITLE
[BUG]: No capacity to activity unit for storage techs 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#175]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

The storage technologies (`PWRBAT...`) do not have a capacity to activity units assigned! This messes up plotting, as we plot the actual battery technologies. 

https://github.com/OSeMOSYS/osemosys_global/blob/fa0d330e55b11ad7ed12cef6e3511867be11db31/workflow/scripts/osemosys_global/TS_data.py#L654-L657

**Comment by trevorb1** [comment]
Little bit of a tricky bug to fix, actually. Since capacity to activity is generated in powerplants, but storage is created in timeslice. Therefore, there would be two rules outputting the same file from the snakemake rules

**Comment by maartenbrinkerink** [comment]
@trevorb1 can you confirm that this is solved after merging #224?
