### ISSUE TITLE
[BUG]: Transmission Plotting for Custom Nodes

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#183]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

If using custom nodes, transmission plotting is skipped as custom nodes do not have centre points. PR #182 implemented this hotfix. 

### Expected Behavior

If custom nodes are added, it would be good to allow users to include centre points to get tranmsission plotting as well! 

### Steps To Reproduce

1. Run the workflow with geographic scope `IDN` and default custom node data 

### Operating System

Linux

**Comment by ajipratama14** [comment]
Thank you @trevorb1 @maartenbrinkerink !

**Comment by maartenbrinkerink** [comment]
@trevorb1 @ajipratama14 this should be solved now with https://github.com/OSeMOSYS/osemosys_global/commit/e995f883bd29d4910119f19351ff906234db2192. Center points for custom nodes can be added in `resources/data/custom_nodes/centerpoints.csv` which is used in `visualise.py` to plot transmission capacities and flows. Closing this issue but let me know if something pops up!
