### ISSUE TITLE
[FEATURE] Integrating the Global Energy Storage Database into the workflow with supporting changes to storage modelling

### ISSUE THREAD

**Issue by maartenbrinkerink** [OSeMOSYS/osemosys_global#187]
### Idea

To utilize the GESDB (by DOE/Sandia) in an integrated fashion. We've used the database before but only added capacities as custom user entries in the config file. This will require some changes in the workflow regarding defining storage parameters (exact changes tbc).

### Suggested Soltuion

I already have a script that pulls data from the GESDB, aggregates the data into aggregate technologies (e.g. short and long duration storage), converts it into OG technology names and defines 'ResidualStorageCapacity.csv', 'StorageMaxChargeRate.csv' and 'StorageMaxDischargeRate.csv'. To be added;

- Add an entry in the config file, separate csv or new config file solely used for naming conventions/grouping (see #68). Also have to make sure that if new entries are being added in the GESDB that its data is still being picked up in OG or that at minimum we'll be notified. E.g. add a line in the code that if new technology types in GESDB occur that a warning pops up that potential data is missing.
- Clarity on how storage is supposed to be modelled going forward as mentioned in #12. @tniet @abhishek0208 
- Clarity on whether all relevant storage parameters are included at the moment as mentioned in #67. @trevorb1

**Comment by tniet** [comment]
@maartenbrinkerink @abhishek0208 - have we come to an agreement on the storage algorithm we're using in OSeMOSYS Global?  The inclusion of the data is likely very easy once we know the algorithm, but I don't want to put a bunch of work in if we're likely to change the algorithm.

Bruno Borba did some work with storage and found the algorithm is quite important to the results...

I know that you did some work on this, Abhi, but I am unclear what the current status is...

**Comment by abhishek0208** [comment]
@maartenbrinkerink @tniet, the existing implementation in osemosys_global uses the Vivid Economics implementation of storage (which is a modification of the original storage equations)
