### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ReemaMohanty** [OSeMOSYS/osemosys_global#200]
### Data In Question

ember_yearly_electricity_data.csv

### Type of data issue.

Missing Data

### Issue

An error shows "Inconsistent use of tabs and spaces in indentation" while running the snakemake command.

**Comment by maartenbrinkerink** [comment]
Hi @ReemaMohanty did you try running the workflow including the latest changes in Master? If so, could you share the error log?

**Comment by ReemaMohanty** [comment]
Yes, I did. I have written the error message below.

TabError in file <string>, line 177:
inconsistent use of tabs and spaces in indentation:
        'resources/data/ember_yearly_electricity_data.csv'
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tokenize.py", line 541, in _generate_tokens_from_c_tokenizer
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tokenize.py", line 537, in _generate_tokens_from_c_tokenizer

**Comment by maartenbrinkerink** [comment]
It does not point to a specific log file for further info on the error? If not could you screenshot the output when the error pops up and share it here? The workflow runs fine on my machine so I doubt that it is an issue related to the specific file.

**Comment by ReemaMohanty** [comment]
<img width="1055" alt="Screenshot 2024-09-19 at 11 39 33" src="https://github.com/user-attachments/assets/38adbd1b-1f8b-42e7-8064-96bc55af44a8">

Please find the screen shot above.

**Comment by maartenbrinkerink** [comment]
@ReemaMohanty can you try removing the file (ember_yearly_electricity_data.csv), remove all folders from the results folder, and rerun the workflow?

**Comment by maartenbrinkerink** [comment]
Indentation issue solved after latest commit on master.
