### ISSUE TITLE
Soft-link with PLEXOS-World

### ISSUE THREAD

**Issue by maartenbrinkerink** [OSeMOSYS/osemosys_global#22]
To be able to assess scenarios coming from OSeMOSYS in PLEXOS-World we need to establish a workflow. An option would be to use the IAMC data template as common data format [https://data.ene.iiasa.ac.at/database/]. The pyam python package is developed by the IAMC that can be used to directly pull data from IAMC databases and can assist with conversion to other data formats (e.g. pandas dataframes).

I'll provide an overview of required input data for the modelling in PLEXOS-World.

**Comment by HauHe** [comment]
Hi @maartenbrinkerink,
have you seen the [osemosys2iamc](https://github.com/oseMOSYS/osemosys2iamc) package yet?
Might be of use for what you are planning.

**Comment by willu47** [comment]
The osemosys2iamc package might be of interest?
