### ISSUE TITLE
[FEATURE] Config entry for demand projections (SpecifiedAnnualDemand)

### ISSUE THREAD

**Issue by maartenbrinkerink** [OSeMOSYS/osemosys_global#220]
### Idea

Following discussions with @SimoneOseiOwusu, to allow users to set demand values for specific nodes in absolute terms or to set relative growth rates for demand by node or at a global level.

### Suggested Soltuion

To set a config entry that overwrites values in `SpecifiedAnnualDemand.csv`. Example possible config entry below;

custom_specified_annual_demand:
INDEA: [[2030, "absolute", 1500], [2040, "relative", 3], [2050, "absolute", 2800]
GLOBAL: [[2030, "relative", 1.5], [2040, "relative", 2], [2050, "relative", 1.5]

1. Demand values to be set either as an absolute value for a given year, with in-between years to be interpolated (nodal only).
2. Or by means of a relative growth rate (nodal or at a global level).

**Comment by maartenbrinkerink** [comment]
@SimoneOseiOwusu @trevorb1 users are now able to set their own demand values in `resources\data\custom_nodes\specified_annual_demand.csv` and `resources\data\custom_nodes\specified_demand_profile.csv` which can be applied to both custom nodes as well as existing nodes. For any data defined in `resources\data\custom_nodes` it will overwrite the baseline workflow values. I will close this issue but let me know if anything is unclear/needs to be changed.

**Comment by trevorb1** [comment]
Thats great! Thanks @maartenbrinkerink!
