### ISSUE TITLE
Extract setup variables into a single yaml file for all scripts

### ISSUE THREAD

**Issue by tniet** [OSeMOSYS/osemosys_global#24]
Make things more portable - instead of having to set the years, country selection, etc. in each script, make one over-arching setup file to make these types of changes.  All scripts can read in this setup file for the variables they need.

**Comment by willu47** [comment]
Check https://docs.python.org/3/library/configparser.html as an alternative

**Comment by willu47** [comment]
Suggest making a start on this by exposing all "configurable parameters" as global variables at the top of scripts. For example:

```python
PLEXOS_URL = "https://dataverse.harvard.edu/api/access/datafile/4008393?format=original&gbrecs=true"
INPUT_PATH = "data"
PLEXOS_DATA = os.path.join(INPUT_PATH, "PLEXOS_World_2015_Gold_V1.1.xlsx")
OUTPUT_PATH = os.path.join("osemosys_global_model", "data")

MODE_LIST = [1, 2]
```

**Comment by maartenbrinkerink** [comment]
@trevorb1 @tniet I think this is mostly covered by means of the config file? Closing the issue for now, if there are still things that could be done here feel free to re-open.
