### ISSUE TITLE
Setup snakemake

### ISSUE THREAD

**Issue by tniet** [OSeMOSYS/osemosys_global#27]
Use snakemake to automate the model generation process.

**Comment by tniet** [comment]
Hey @trevorb1 - I'm tagging you to this action item as I think you might both enjoy figuring out snakemake, and be able to make some quick progress setting up some processes for this.  Happy to help figure the pieces out/discuss what we're looking to do.

**Comment by trevorb1** [comment]
Totally! I will start looking into it

**Comment by willu47** [comment]
There's some initial work on the [`add_snakemake` branch](https://github.com/OSeMOSYS/osemosys_global/tree/add_snakemake)
