### ISSUE TITLE
Add in transmission costs

### ISSUE THREAD

**Issue by tniet** [OSeMOSYS/osemosys_global#51]

**Comment by maartenbrinkerink** [comment]
@tniet The transmission cost dataset is mentioned in issue #46. For now a good start, can always update it if your PhD project goes through.

**Comment by tniet** [comment]
Thanks @maartenbrinkerink!

**Comment by maartenbrinkerink** [comment]
Workflow is currently linked to the raw PLEXOS-World data including transmission costs. Future updates are mentioned in #186. Closing this issue.
