### ISSUE TITLE
Add progress messages to scripts

### ISSUE THREAD

**Issue by tniet** [OSeMOSYS/osemosys_global#52]
Current scripts don't show their progress on the command line.  Add a few print statements that indicate progress to the user.

**Comment by willu47** [comment]
I would recommend using the Python logging library (built into the core code) or tfqm which provides a one line progress bar for loops.

**Comment by maartenbrinkerink** [comment]
@trevorb1 I believe we currently have progress messages in the workflow indicating the start/end of individual scripts? Closing this issue for now, if this is presumptuous feel free to reopen.
