### ISSUE TITLE
Model file used to run with the python script needs to be edited to run

### ISSUE THREAD

**Issue by tniet** [OSeMOSYS/osemosys_global#53]
The model file needed to run OSeMOSYS global is not the same as the fast code at https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/tree/master/src.  Do we need to advocate for an additional model file in the OSeMOSYS repo that is setup for the python script or for the OSeMOSYS fast code to be changed to be python script compatible?
My initial view is that we should advocate for the fast code to be migrated to run by default with the script - this is the fastest way to run the model, and the fast code should be the fastest way to run the model.
Other thoughts?  If we have a preferred structure we can ask for this on the OSeMOSYS repo.

**Comment by willu47** [comment]
Ideally, you'd use a specific release of the OSeMOSYS code (e.g. downloaded from Github releases on OSeMOSYS_GNU_MathProg).

**Comment by tniet** [comment]
Yes @willu47, but the fastest way to run the model isn't with a released version - maybe (per your note at https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/issues/66#issuecomment-827865127), we need to consider what the fast code is meant to be?  I would argue that it should be the fastest way to run models (I'll comment on the MathProg issue as well).

On a related note, I wonder if @trevorb1 can run with the fast and the script and let us know the difference in processing times?

**Comment by tniet** [comment]
Hey @willu47 - yes, ideally we'd use a release version.  However, that's not the fastest way to run the model as GNU MathProg isn't very efficient at creating the MODEx crossover sets.  This is related to the issue at https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/issues/66 that you posted and I will comment further there.

Maybe @trevorb1 can run with the fast code and with the pre-processing script and let us know the time difference?

**Comment by trevorb1** [comment]
@tniet Definitely! I was hoping to have the answer for you today on the time differences, but the pre-processed file has been running all day and hasn't solved yet. I will update on time differences once I have that information.

**Comment by maartenbrinkerink** [comment]
@trevorb1 @tniet this is above my paygrade. Is this still relevant or can it be closed?

**Comment by trevorb1** [comment]
I think we can close this; thanks for flagging @maartenbrinkerink! We have a model file that works, and discussion on maintaining different versions of the model file already exist on the main repo, I believe.
