### ISSUE TITLE
Missing TotalAnnualMaxCapacity Data

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#62]
This includes TotalAnnualMaxCapacity and TotalAnnualMaxCapacityInvestment data

**Comment by maartenbrinkerink** [comment]
This exists for RES technologies with yearly limits derived based on total resource potentials. It's not existing for thermal plants etc. but also don't think that is an urgent development so closing this issue for now (feel free to reopen if necessary).
