### ISSUE TITLE
Missing TotalAnnualMinCapacity Data

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#63]
This includes TotalAnnualMinCapacity and TotalAnnualMinCapacityInvestment data

**Comment by maartenbrinkerink** [comment]
I personally don't think that forcing minimum capacity investments of a given technology should be part of an optimization. I.e. the model should identify itself that certain capacities are required/optimal. Fixing investments based on planned capacities can be done through custom user inputs. Closing this issue for now.
