### ISSUE TITLE
Missing TotalTechnologyActivityLowerLimit Data

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#65]
This includes TotalTechnologyAnnualActivityLowerLimit and TotalTechnologyModelPeriodActivityLowerLimit data

**Comment by maartenbrinkerink** [comment]
At this point the availability/activity of technologies are controlled by both Capacity Factors and Availability Factors. Also including limits on activity might be overcomplicating the optimization. Closing this issue for now but feel free to reopen.
