### ISSUE TITLE
Geographic filter transmission lines

### ISSUE THREAD

**Issue by maartenbrinkerink** [OSeMOSYS/osemosys_global#74]
Right now it seems that the spatial filtering for transmission lines is not working fully accurate, e.g. in a sample model of AFG & IND the results also include e.g. technology "TRNBGDXXINDNE".

**Comment by kkuling** [comment]
Attached is the modified geo-filter script used to remove these technologies:
[OPG_geographic_filter.py.zip](https://github.com/OSeMOSYS/osemosys_global/files/7394143/OPG_geographic_filter.py.zip)

**Comment by maartenbrinkerink** [comment]
To my understanding this has been fixed with #122 as discussed in #114. The potential enhancement of covering trade to regions/countries that are not in the actual geographical scope is not included in the workflow yet but is discussed in #116 hence closing this issue as it is duplicate.
