### ISSUE TITLE
Add TimeSlice Defenitions in the Config File 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#76]

**Comment by trevorb1** [comment]
How are we wanting to add timeslice definitions to the config file? Right now it looks like the timeslice structure is defined in `OPG_TS_Data.py` here... 

![image](https://user-images.githubusercontent.com/67297083/142085358-c3171fdc-2033-4c58-8972-c2d34f7f3a54.png)

In the config file we currently only give an option to include daytype as True or False. Are we wanting to go further and give more flexibility? (ie. separate by hours, days, months, seasons)

**Comment by tniet** [comment]
@abhishek0208 - Let's also adjust the TS naming convention to make it S01D01 so we can have a 2 digit season and a 2 digit day.

**Comment by trevorb1** [comment]
Added daypart and seasons to config file. In the most recent `ts_seasons.csv` file there are also columns for month name (January, February, ...) and days in the season. Instead of putting these into the config file, its probably just easier to use the datetime python library. These columns are only used in the visualization script, so I will hold off on making that change until we are all on the same page with the current state of everything

**Comment by maartenbrinkerink** [comment]
@trevorb1 @tniet I think that the current implementation of time slices in the config file is appropriate? Can we close this issue until we have a reason (and bandwidth) to make further adjustments?

**Comment by trevorb1** [comment]
Fine by me! :)
