### ISSUE TITLE
OPG_DemandProjections creates input data files

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/osemosys_global#83]
The demand projection script creates new versions of the `data/Final_Electricity_Demand_Nodal_Yearly.csv` and  `data/Final_Electricity_Peak_Demand_Nodal_Yearly.csv` files. These arn't used anywhere else in the OPG scrips (at least that I saw), and Im a little confused why we are creating input files (`data/` folder) from the OPG scripts? 

No big issue, but they always pop up as modified by git!

**Comment by maartenbrinkerink** [comment]
Let me have a look at this. Those DFs are not used right now and should therefore also not be exported to csv. That said, I don't want to remove the DFs from the script in case we want to start adjusting relative peak demand for future model runs. Feel free to assign me to this issue @trevorb1

**Comment by maartenbrinkerink** [comment]
@trevorb1 i've made the relevant changes, including updates to demand projection, to a seperate branch. Can you review and merge to master?

**Comment by trevorb1** [comment]
Thanks @maartenbrinkerink ! Quick question, what branch did you make the changes on? Im not seeing a recent branch pushed by you? I may just be missing it though?

**Comment by maartenbrinkerink** [comment]
My apologies, can find it now in pull requests..
